### ISSUE TITLE
Issues with Login Context

### ISSUE THREAD

**Issue by HassanAlthaf** [signes-pl/vbulletin-api-php#1]
Current, it returns the sessionhash, etc. But when I try redirecting to the forum after login, the user is not actually logged in on the forum. What am I doing wrong? I'm using the exact same code as you.

**Comment by muscle-rhnkyr** [comment]
@HassanAlthaf if you still need (after 2 years :)) I did handle like this 👍 

somewhere in your code :

        $apiConfig    = new ApiConfig('api_key', 'abc', 'mbc', '1', 'Client', '1');
        $apiConnector = new GuzzleProvider('https://forum.yourdomain.com/');
        $api = new Api($apiConfig, $apiConnector);
        $loginUserContext = new Login('user', 'password');

        $response = $api->callContextRequest($loginUserContext);

        $timeout = time() + (30 * 24 * 60 * 60);

        setcookie('vb_sessionhash', $response['sessionhash'], $timeout, '/', 'yourdomain.com', false, true); // or your custom prefix xx_sessionhash
        setcookie('vb_userid', $response['userid'], $timeout, '/', 'yourdomain.com', false, true);
        setcookie('vb_password', $response['password'], $timeout, '/', 'yourdomain.com', false, true);

      return redirect()->to('https://forum.yourdomain.com'); //it is laravel redirect handle it in your side


Beside your cookiedomain has to be main domain otherwise it won't work.

**Comment by HassanAlthaf** [comment]
Thanks for sharing buddy. The project is long done, but we skipped this functionality since most of the requirements could not be met. Once again, thanks again for sharing.
